// <auto-generated />
using KmaOoad18.Leanware.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leanware.Web.Data.Migrations
{
    [DbContext(typeof(LeanwareContext))]
    [Migration("20181015090936_20181015T1209262058")]
    partial class _20181015T1209262058
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("KmaOoad18.Leanware.Web.Models.UserStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("UserStories");
                });
#pragma warning restore 612, 618
        }
    }
}
